name: Deploy to Heroku
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Heroku CLI
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ico-nfhs-multipage
    - name: Deploy to Heroku
      run: |
        heroku login -i
        heroku container:login
        heroku container:push web -a ico-nfhs-multipage
        heroku container:release web -a ico-nfhs-multipage